import type { FurnitureKind } from "./types";

export type CatalogCategory =
  | "Salon"
  | "Chambre"
  | "Cuisine"
  | "Salle de bain"
  | "Bureau"
  | "Buanderie"
  | "Extérieur"
  | "Divers";

export type CatalogItem = {
  kind: FurnitureKind;
  label: string;
  category: CatalogCategory;
  width: number; // cm
  height: number; // cm (depth in plan view)
  zHeight?: number; // cm (elevation), optional — otherwise sections.ts default
  color: string;
  anchorToWall?: boolean;
};

export const CATALOG: CatalogItem[] = [
  // ---- Salon ----
  {
    kind: "sofa",
    label: "Canapé 3 places",
    category: "Salon",
    width: 220,
    height: 90,
    zHeight: 85,
    color: "#b8a68a",
  },
  {
    kind: "sofa",
    label: "Canapé 2 places",
    category: "Salon",
    width: 160,
    height: 90,
    zHeight: 85,
    color: "#b8a68a",
  },
  {
    kind: "sofa_l",
    label: "Canapé d'angle",
    category: "Salon",
    width: 260,
    height: 180,
    zHeight: 85,
    color: "#8b7a5f",
  },
  {
    kind: "armchair",
    label: "Fauteuil",
    category: "Salon",
    width: 85,
    height: 85,
    zHeight: 90,
    color: "#c9b89a",
  },
  {
    kind: "coffee_table",
    label: "Table basse",
    category: "Salon",
    width: 120,
    height: 60,
    zHeight: 40,
    color: "#8b6f47",
  },
  {
    kind: "tv_console",
    label: "Meuble TV",
    category: "Salon",
    width: 160,
    height: 40,
    zHeight: 50,
    color: "#4a3a2a",
    anchorToWall: true,
  },
  {
    kind: "tv",
    label: 'TV murale 55"',
    category: "Salon",
    width: 125,
    height: 10,
    zHeight: 75,
    color: "#0a0a0a",
    anchorToWall: true,
  },
  {
    kind: "bookshelf",
    label: "Bibliothèque",
    category: "Salon",
    width: 180,
    height: 35,
    zHeight: 200,
    color: "#6b5842",
    anchorToWall: true,
  },
  { kind: "rug", label: "Tapis", category: "Salon", width: 200, height: 300, color: "#c9a961" },
  {
    kind: "fireplace",
    label: "Cheminée",
    category: "Salon",
    width: 140,
    height: 40,
    zHeight: 220,
    color: "#c8b89a",
    anchorToWall: true,
  },
  {
    kind: "wood_stove",
    label: "Poêle à bois",
    category: "Salon",
    width: 60,
    height: 55,
    zHeight: 110,
    color: "#1a1a1a",
  },

  // ---- Chambre ----
  {
    kind: "bed",
    label: "Lit double 160",
    category: "Chambre",
    width: 160,
    height: 200,
    zHeight: 55,
    color: "#d4c4a8",
  },
  {
    kind: "bed",
    label: "Lit king 180",
    category: "Chambre",
    width: 180,
    height: 200,
    zHeight: 55,
    color: "#d4c4a8",
  },
  {
    kind: "bed_single",
    label: "Lit simple 90",
    category: "Chambre",
    width: 90,
    height: 200,
    zHeight: 55,
    color: "#d4c4a8",
  },
  {
    kind: "nightstand",
    label: "Table de nuit",
    category: "Chambre",
    width: 45,
    height: 40,
    zHeight: 55,
    color: "#8b7355",
  },
  {
    kind: "wardrobe",
    label: "Armoire 2 portes",
    category: "Chambre",
    width: 120,
    height: 60,
    zHeight: 220,
    color: "#6b5842",
    anchorToWall: true,
  },
  {
    kind: "wardrobe",
    label: "Armoire 3 portes",
    category: "Chambre",
    width: 180,
    height: 60,
    zHeight: 220,
    color: "#6b5842",
    anchorToWall: true,
  },
  {
    kind: "dresser",
    label: "Commode",
    category: "Chambre",
    width: 110,
    height: 45,
    zHeight: 90,
    color: "#7a5d3a",
    anchorToWall: true,
  },

  // ---- Cuisine ----
  {
    kind: "kitchen_base",
    label: "Caisson 60",
    category: "Cuisine",
    width: 60,
    height: 60,
    zHeight: 90,
    color: "#e8e4dc",
    anchorToWall: true,
  },
  {
    kind: "kitchen_base",
    label: "Caisson 80",
    category: "Cuisine",
    width: 80,
    height: 60,
    zHeight: 90,
    color: "#e8e4dc",
    anchorToWall: true,
  },
  {
    kind: "kitchen_base",
    label: "Caisson 100",
    category: "Cuisine",
    width: 100,
    height: 60,
    zHeight: 90,
    color: "#e8e4dc",
    anchorToWall: true,
  },
  {
    kind: "kitchen_upper",
    label: "Meuble haut 80",
    category: "Cuisine",
    width: 80,
    height: 35,
    zHeight: 70,
    color: "#e8e4dc",
    anchorToWall: true,
  },
  {
    kind: "kitchen_island",
    label: "Îlot central",
    category: "Cuisine",
    width: 200,
    height: 100,
    zHeight: 90,
    color: "#c9b89a",
  },
  {
    kind: "sink",
    label: "Évier 1 bac",
    category: "Cuisine",
    width: 60,
    height: 55,
    zHeight: 90,
    color: "#c8c8c8",
    anchorToWall: true,
  },
  {
    kind: "sink",
    label: "Évier 2 bacs",
    category: "Cuisine",
    width: 100,
    height: 55,
    zHeight: 90,
    color: "#c8c8c8",
    anchorToWall: true,
  },
  {
    kind: "stove",
    label: "Plaque de cuisson",
    category: "Cuisine",
    width: 60,
    height: 55,
    zHeight: 90,
    color: "#1a1a1a",
    anchorToWall: true,
  },
  {
    kind: "oven",
    label: "Four",
    category: "Cuisine",
    width: 60,
    height: 55,
    zHeight: 90,
    color: "#2a2a2a",
    anchorToWall: true,
  },
  {
    kind: "microwave",
    label: "Micro-ondes",
    category: "Cuisine",
    width: 50,
    height: 35,
    zHeight: 30,
    color: "#2a2a2a",
  },
  {
    kind: "hood",
    label: "Hotte",
    category: "Cuisine",
    width: 80,
    height: 45,
    zHeight: 60,
    color: "#a0a0a0",
    anchorToWall: true,
  },
  {
    kind: "dishwasher",
    label: "Lave-vaisselle",
    category: "Cuisine",
    width: 60,
    height: 60,
    zHeight: 90,
    color: "#d0d0d0",
    anchorToWall: true,
  },
  {
    kind: "fridge",
    label: "Frigo",
    category: "Cuisine",
    width: 70,
    height: 65,
    zHeight: 180,
    color: "#d5d5d5",
    anchorToWall: true,
  },
  {
    kind: "fridge",
    label: "Frigo américain",
    category: "Cuisine",
    width: 90,
    height: 70,
    zHeight: 180,
    color: "#d5d5d5",
    anchorToWall: true,
  },
  {
    kind: "dining",
    label: "Table à manger 6p",
    category: "Cuisine",
    width: 180,
    height: 90,
    zHeight: 75,
    color: "#8b7355",
  },
  {
    kind: "dining",
    label: "Table à manger 4p",
    category: "Cuisine",
    width: 120,
    height: 80,
    zHeight: 75,
    color: "#8b7355",
  },
  {
    kind: "chair",
    label: "Chaise",
    category: "Cuisine",
    width: 45,
    height: 50,
    zHeight: 90,
    color: "#6b5842",
  },

  // ---- Salle de bain ----
  {
    kind: "toilet",
    label: "WC",
    category: "Salle de bain",
    width: 40,
    height: 65,
    zHeight: 80,
    color: "#f6f6f2",
    anchorToWall: true,
  },
  {
    kind: "bidet",
    label: "Bidet",
    category: "Salle de bain",
    width: 40,
    height: 60,
    zHeight: 40,
    color: "#f6f6f2",
    anchorToWall: true,
  },
  {
    kind: "bath",
    label: "Baignoire 170",
    category: "Salle de bain",
    width: 170,
    height: 75,
    zHeight: 55,
    color: "#f6f6f2",
    anchorToWall: true,
  },
  {
    kind: "bath",
    label: "Baignoire d'angle",
    category: "Salle de bain",
    width: 140,
    height: 140,
    zHeight: 55,
    color: "#f6f6f2",
  },
  {
    kind: "shower",
    label: "Douche 80×80",
    category: "Salle de bain",
    width: 80,
    height: 80,
    zHeight: 210,
    color: "#dfe6ea",
    anchorToWall: true,
  },
  {
    kind: "shower",
    label: "Douche 120×80",
    category: "Salle de bain",
    width: 120,
    height: 80,
    zHeight: 210,
    color: "#dfe6ea",
    anchorToWall: true,
  },
  {
    kind: "vanity",
    label: "Meuble vasque 80",
    category: "Salle de bain",
    width: 80,
    height: 50,
    zHeight: 85,
    color: "#c9b89a",
    anchorToWall: true,
  },
  {
    kind: "vanity",
    label: "Meuble vasque 120",
    category: "Salle de bain",
    width: 120,
    height: 50,
    zHeight: 85,
    color: "#c9b89a",
    anchorToWall: true,
  },
  {
    kind: "radiator",
    label: "Radiateur",
    category: "Salle de bain",
    width: 60,
    height: 10,
    zHeight: 60,
    color: "#e8e8e8",
    anchorToWall: true,
  },
  {
    kind: "towel_rack",
    label: "Sèche-serviettes",
    category: "Salle de bain",
    width: 50,
    height: 8,
    zHeight: 120,
    color: "#e8e8e8",
    anchorToWall: true,
  },

  // ---- Bureau ----
  {
    kind: "desk",
    label: "Bureau 140",
    category: "Bureau",
    width: 140,
    height: 70,
    zHeight: 75,
    color: "#8b7355",
  },
  {
    kind: "desk",
    label: "Bureau d'angle",
    category: "Bureau",
    width: 160,
    height: 160,
    zHeight: 75,
    color: "#8b7355",
  },
  {
    kind: "chair",
    label: "Chaise de bureau",
    category: "Bureau",
    width: 60,
    height: 60,
    zHeight: 100,
    color: "#2a2a2a",
  },
  {
    kind: "bookshelf",
    label: "Étagère bureau",
    category: "Bureau",
    width: 80,
    height: 30,
    zHeight: 180,
    color: "#6b5842",
    anchorToWall: true,
  },

  // ---- Buanderie ----
  {
    kind: "washer",
    label: "Lave-linge",
    category: "Buanderie",
    width: 60,
    height: 60,
    zHeight: 85,
    color: "#e0e0e0",
    anchorToWall: true,
  },
  {
    kind: "washer",
    label: "Sèche-linge",
    category: "Buanderie",
    width: 60,
    height: 60,
    zHeight: 85,
    color: "#e0e0e0",
    anchorToWall: true,
  },

  // ---- Extérieur ----
  {
    kind: "garden_table",
    label: "Table de jardin",
    category: "Extérieur",
    width: 160,
    height: 90,
    zHeight: 75,
    color: "#6b5842",
  },
  {
    kind: "garden_chair",
    label: "Chaise jardin",
    category: "Extérieur",
    width: 50,
    height: 55,
    zHeight: 85,
    color: "#8b7355",
  },
  {
    kind: "bbq",
    label: "Barbecue",
    category: "Extérieur",
    width: 110,
    height: 60,
    zHeight: 100,
    color: "#2a2a2a",
  },
  {
    kind: "parasol",
    label: "Parasol",
    category: "Extérieur",
    width: 250,
    height: 250,
    zHeight: 240,
    color: "#c9b89a",
  },
  {
    kind: "pool",
    label: "Piscine",
    category: "Extérieur",
    width: 800,
    height: 400,
    zHeight: 20,
    color: "#6ec2e0",
  },
  {
    kind: "plant",
    label: "Plante",
    category: "Extérieur",
    width: 50,
    height: 50,
    zHeight: 100,
    color: "#7a9270",
  },

  // ---- Divers ----
  {
    kind: "staircase",
    label: "Escalier droit",
    category: "Divers",
    width: 100,
    height: 300,
    zHeight: 250,
    color: "#a08a6c",
  },
  {
    kind: "staircase",
    label: "Escalier quart tour.",
    category: "Divers",
    width: 200,
    height: 200,
    zHeight: 250,
    color: "#a08a6c",
  },
];
